### ISSUE TITLE
Configure provider with Access Token

### ISSUE THREAD

**Issue by wow-anton** [scastria/terraform-provider-apigee#1]
Hi @scastria,

Our organization enforces MFA which means that Basic Auth won't work [(source)](https://docs.apigee.com/api-platform/system-administration/management-api-overview#warning)

Are there any plans to add support for configuring the provider with Access Tokens instead?

Thanks,
Anton

**Comment by scastria** [comment]
Good idea. I should have it done by tomorrow.

**Comment by scastria** [comment]
When v0.1.16 is done building, it should give you what you need.

**Comment by wow-anton** [comment]
That did it, thanks!
