### ISSUE TITLE
User creation

### ISSUE THREAD

**Issue by dheerujava** [scastria/terraform-provider-apigee#10]
When I am using the 
resource "apigee_user" "MyUser" {
  email_id = "XXXXXX@gmail.com"
  first_name = "John"
  last_name = "Smith"
  password = "XXXX"
}
with my credential , every time I am getting below error:
Error: Status 403: Message: Forbidden:  during apply .
Please suggest what else is needed in configuration

**Comment by scastria** [comment]
I need some more information.  What Apigee server are you talking to?  Is it a private OPDK installation or a public cloud version?  In other words, can you send me your provider configuration (with sensitive stuff removed, of course)?

If you look at the main doc page here: https://registry.terraform.io/providers/scastria/apigee/latest/docs you will see that there are 3 types of Apigee servers that are supported, but not all of them support all resource types.  For example, Apigee Edge for Public Cloud does NOT support creating users as shown in these docs: https://apidocs.apigee.com/docs/users/1/overview.

**Comment by scastria** [comment]
Can I close this issue?
