### ISSUE TITLE
Importing a Sharedflow deployment is not working || Crash Report

### ISSUE THREAD

**Issue by Devajeet1995** [scastria/terraform-provider-apigee#15]
Terraform crashed after using the apigee repo. 
[crash.log](https://github.com/scastria/terraform-provider-apigee/files/6037231/crash.log)

Terraform version - 0.14.7
Steps to reproduce
1. terraform init
2. terraform apply

**Comment by scastria** [comment]
In order for me to investigate further, I need your tf configure file that you are trying to apply.  Plus, I don't see any crashes in your crash.log file.

**Comment by Devajeet1995** [comment]
When I run terraform plan I see this crash. Also I have multiple tf files.

**Comment by Devajeet1995** [comment]
Yesterday it was running but now I am getting this crash.

**Comment by scastria** [comment]
I would only need the tf file that describes the resource that is causing the crash.  I don't know which resource is causing the crash because I don't see any crash in the crash.log you sent me.  What is the last log message printed before the crash happens?

**Comment by Devajeet1995** [comment]
Okay, so I also don't know which file is causing terraform to crash so I will upload it all and you can have a check.
[create_user.txt](https://github.com/scastria/terraform-provider-apigee/files/6043276/create_user.txt)
[helloworld.txt](https://github.com/scastria/terraform-provider-apigee/files/6043277/helloworld.txt)
[proxy_deploy.txt](https://github.com/scastria/terraform-provider-apigee/files/6043278/proxy_deploy.txt)
[proxy_import.txt](https://github.com/scastria/terraform-provider-apigee/files/6043279/proxy_import.txt)
[sharedflow_deploy.txt](https://github.com/scastria/terraform-provider-apigee/files/6043280/sharedflow_deploy.txt)
[sharedflows_import.txt](https://github.com/scastria/terraform-provider-apigee/files/6043281/sharedflows_import.txt)
[provider.txt](https://github.com/scastria/terraform-provider-apigee/files/6043292/provider.txt)

**Comment by Devajeet1995** [comment]
Also, one thing to ask. Do you have any other provider which does the migration things through terraform like migrating API proxies, shared flows, etc, and not really creating a new one?

**Comment by scastria** [comment]
I need to see the crash log. As I said above, I do not see a crash in the crash log you sent. 

Are you expecting me to run plan or apply using YOUR credentials?

**Comment by scastria** [comment]
Regarding migration, are you asking if there is a way to migrate existing Apigee proxies to TerraForm control? If so, the answer is yes.  You can download an existing Apigee proxy to your local machine. Then you can run terraform import to import that into TerraForm and it doesn’t delete it create anything.

**Comment by Devajeet1995** [comment]
> I need to see the crash log. As I said above, I do not see a crash in the crash log you sent.
> 
> Are you expecting me to run plan or apply using YOUR credentials?

Yes please

**Comment by Devajeet1995** [comment]
> Regarding migration, are you asking if there is a way to migrate existing Apigee proxies to TerraForm control? If so, the answer is yes. You can download an existing Apigee proxy to your local machine. Then you can run terraform import to import that into TerraForm and it doesn’t delete or create anything.

Yes I understood what you are saying but what I want is a script where I can mention the source account to pick the zip bundle and the destination account to place that bundle. I mean with this apigee provider I have to download the zip in my local and then with your script import it to the destination account. Can it be done without having to download and storing it into local machine?

**Comment by scastria** [comment]
I am not sure on that.

On the crash, please send me something that shows a crash.

**Comment by Devajeet1995** [comment]
Thanks Scastria. I will figure it out by myself then. But can you please tell me where do I add the override flag that specifies whether the new deployment replaces other deployed revisions? It would be really helpful because as of now I am getting "Only one revision can be deployed at a time, use the                                                                                         override flag to replace." this error. And now I can't run other files.
![override](https://user-images.githubusercontent.com/36272733/109306607-67985a80-7865-11eb-851b-fcc0d59dcc21.PNG)

**Comment by scastria** [comment]
The override flag is automatically added during updates.  Therefore, you can not create a new proxy_deployment from Terraform if the proxy is already deployed.  You must first import it into Terraform so that your proxy_deployment resource now knows what revision of the proxy is currently deployed.  Then when you run apply, it will try to perform an update, if necessary and automatically add the override flag.

**Comment by Devajeet1995** [comment]
So then why am I getting this error "one revision can be deployed at a time". It should override it.

**Comment by scastria** [comment]
Correct. It sounds like it is trying to CREATE a proxy deployment instead of UPDATE a proxy deployment which means you need to first IMPORT the existing proxy deployment.

**Comment by Devajeet1995** [comment]
Yes I did that. But in the second apply, it should update the revision is what my concern is.

**Comment by Devajeet1995** [comment]
Ok so I need to add the id argument is what your suggestion is.

**Comment by scastria** [comment]
No, you should never add the Id parameter in a TF file. Running the import command should fill in the id parameter for you into your tf state file. That should cause the next apply to do an update and add the override flag. 

Can you post the output of the plan command? It should not say it is going to create anything. It should say it will update something.

**Comment by Devajeet1995** [comment]
Whenever I am doing the import it is asking me to enter the address as the syntax goes like
terraform import  ADDRESS   ID.. I have put the ID as you mentioned but what I need to put in place of "ADDRESS"?

**Comment by Devajeet1995** [comment]
After the import I am getting this
![image](https://user-images.githubusercontent.com/36272733/109642115-9588e200-7b78-11eb-98b1-2af9aa1c651a.png)

**Comment by scastria** [comment]
That shows you have imported the apigee_proxy which is great, but the override flag relates to an apigee_proxy_deployment.  So have you also imported the apigee_proxy_deployment?

**Comment by Devajeet1995** [comment]
Thanks that worked. However, for the shared flows it's still showing me the error. I tried importing the shared flow but while importing the deployment I am getting a crash. Please check if my syntax of importing sharedflow deployment is correct or not
terraform import apigee_shared_flow_deployment.deploy_shared_flow_pre sandbox:PreFlow

**Comment by scastria** [comment]
That looks right to me, also, a terraform provider should never crash.  So we are back to me needing to see the crash log.

**Comment by Devajeet1995** [comment]
this is the crash report after running this
terraform import apigee_shared_flow_deployment.deploy_shared_flow_pre sandbox:PreFlow
[crash.log](https://github.com/scastria/terraform-provider-apigee/files/6088776/crash.log)

**Comment by scastria** [comment]
I can see the "panic" in your crash log so now I finally have a place to look for the bug...  Thanks.

**Comment by scastria** [comment]
I believe the problem is that the new Google version of Apigee has slightly different outputs from their REST APIs.  I ran into this with a previous reported bug with proxies but forgot to apply the fix for shared flows too.  I don't have a Google Apigee account anymore to test so I will do my best in copying my fix from proxies over to shared flows.

**Comment by Devajeet1995** [comment]
> I believe the problem is that the new Google version of Apigee has slightly different outputs from their REST APIs. I ran into this with a previous reported bug with proxies but forgot to apply the fix for shared flows too. I don't have a Google Apigee account anymore to test so I will do my best in copying my fix from proxies over to shared flows.

Thanks Scastria, that would be very much appreciated.

**Comment by scastria** [comment]
ok, I am not able to test this because I don't have a Google Apigee account, but I think this might work.  Please try v0.1.37 when it is done building.

If it doesn't work, then please run the following REST request and send me the response so I can double check the REST response versus what my provider is expecting:

GET /v1/organizations/hybrid-300708/environments/sandbox/sharedflows/PreFlow/deployments

**Comment by Devajeet1995** [comment]
Alright, Scastria. I will do that as early as possible and let you know about it's status.

**Comment by Devajeet1995** [comment]
Hi Scastria, I am getting the following response upon hitting the above endpoint
{
    "deployments": [
        {
            "environment": "test-env",
            "apiProxy": "CORS-Preflow",
            "revision": "1",
            "deployStartTime": "1615362477678"
        }
    ]
}

However, I am still not getting where do I have to update the version on my terraform code to change to version 0.1.37

**Comment by scastria** [comment]
If you are using TerraForm 14 or later, you should have a lock file laying around. Delete that lock file and rerun TerraForm init and it should download the latest providers.

**Comment by Devajeet1995** [comment]
Hi, Scastria thanks for the response. I applied your instruction and also imported the deployments for all the proxies and the shared flows but getting the below errors.

----------------------------------------------------------
Error: Status 400: Message: Bad Request: {                                                                                                                                "error": {                                                                                                                                                                "code": 400,                                                                                                                                                            "message": "deployment validations failed",                                                                                                                             "status": "FAILED_PRECONDITION",                                                                                                                                        "details": [                                                                                                                                                              {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.PreconditionFailure",                                                                                                          "violations": [                                                                                                                                                           {                                                                                                                                                                         "type": "CONFLICTING_DEPLOYMENT",                                                                                                                                       "subject": "organizations/hybrid-apigee-neos/apis/oauth/revisions/1",                                                                                                   "description": "Only one revision can be deployed at a time, use the override flag to replace."                                                                       }]                                                                                                                                                                     },                                                                                                                                                                      {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.RequestInfo",                                                                                                                  "requestId": "9960491530307081173"                                                                                                                                    }] }   
}
-----------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Error: Status 400: Message: Bad Request: {                                                                                                                                "error": {                                                                                                                                                                "code": 400,                                                                                                                                                            "message": "deployment validations failed",                                                                                                                             "status": "FAILED_PRECONDITION",                                                                                                                                        "details": [                                                                                                                                                              {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.PreconditionFailure",                                                                                                          "violations": [                                                                                                                                                           {                                                                                                                                                                         "type": "CONFLICTING_DEPLOYMENT",                                                                                                                                       "subject": "organizations/hybrid-apigee-neos/apis/SET-KVM-Values/revisions/1",                                                                                          "description": "Only one revision can be deployed at a time, use the override flag to replace."                                                                       } ]                                                                                                                                                                     },                                                                                                                                                                      {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.RequestInfo",                                                                                                                  "requestId": "11227717501924928893"                                                                                                                                   } ]                                                                                                                                                                     }  
}
-------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Error: Status 400: Message: Bad Request: {                                                                                                                                "error": {                                                                                                                                                                "code": 400,                                                                                                                                                            "message": "deployment validations failed",                                                                                                                             "status": "FAILED_PRECONDITION",                                                                                                                                        "details": [                                                                                                                                                              {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.PreconditionFailure",                                                                                                          "violations": [                                                                                                                                                           {                                                                                                                                                                         "type": "CONFLICTING_DEPLOYMENT",                                                                                                                                       "subject": "organizations/hybrid-apigee-neos/apis/MerchantAPI/revisions/1",                                                                                             "description": "Only one revision can be deployed at a time, use the override flag to replace."                                                                       }]                                                                                                                                                                     },                                                                                                                                                                      {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.RequestInfo",                                                                                                                  "requestId": "211182757807888209"                                                                                                                                     }]}         
}
----------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Error: Status 400: Message: Bad Request: {                                                                                                                                "error": {                                                                                                                                                                "code": 400,                                                                                                                                                            "message": "revision organizations/hybrid-apigee-neos/apis/JWE-Encrypt-Decrypt/revisions/2 is already deployed",                                                        "status": "FAILED_PRECONDITION",                                                                                                                                        "details": [                                                                                                                                                              {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.RequestInfo",                                                                                                                  "requestId": "17061189274355089970"                                                                                                                                   }]}                  
}
-------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Error: Status 400: Message: Bad Request: {                                                                                                                                "error": {                                                                                                                                                                "code": 400,                                                                                                                                                            "message": "revision organizations/hybrid-apigee-neos/sharedflows/CORS-Postflow/revisions/2 is already deployed",                                                       "status": "FAILED_PRECONDITION",                                                                                                                                        "details": [                                                                                                                                                              {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.RequestInfo",                                                                                                                  "requestId": "8616161659045413009"                                                                                                                                    }]}
}
--------------------------------------------------------------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Error: Status 400: Message: Bad Request: {                                                                                                                                "error": {                                                                                                                                                                "code": 400,                                                                                                                                                            "message": "deployment validations failed",                                                                                                                             "status": "FAILED_PRECONDITION",                                                                                                                                        "details": [                                                                                                                                                              {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.PreconditionFailure",                                                                                                          "violations": [                                                                                                                                                           {                                                                                                                                                                         "type": "CONFLICTING_DEPLOYMENT",                                                                                                                                       "subject": "organizations/hybrid-apigee-neos/apis/Mock-API/revisions/1",                                                                                                "description": "Only one revision can be deployed at a time, use the override flag to replace."                                                                       }]                                                                                                                                                                     },                                                                                                                                                                      {                                                                                                                                                                         "@type": "type.googleapis.com/google.rpc.RequestInfo",                                                                                                                  "requestId": "11015839941420138919"                                                                                                                                   }]}                                                                                                                                                                     }

**Comment by Devajeet1995** [comment]
Sharing the state file as well
[terraform.tfstate.docx](https://github.com/scastria/terraform-provider-apigee/files/6121751/terraform.tfstate.docx)

**Comment by Devajeet1995** [comment]
Sharing the state file as well. (since .tf extension is nt allowed in github so I converted to docx)
[terraformtfstate.docx](https://github.com/scastria/terraform-provider-apigee/files/6121762/terraformtfstate.docx)

**Comment by scastria** [comment]
If I look at your state file and I take the very first error above, I can see that your state files DOES NOT contain an apigee_proxy_deployment for "oauth".  I can see the apigee_proxy itself for oauth, but not its deployment.  That would definitely explain the error.  That would mean your plan is trying to create a brand new apigee_proxy_deployment instead of updating an existing one.

This is the same error as before.  You must import the existing apigee_proxy_deployment for oauth FIRST.  You said you imported all deployments, but your state file says that you have NOT.

**Comment by Devajeet1995** [comment]
It resolved. Thanks Scastria

**Comment by Devajeet1995** [comment]
Hi Scastria. I think when I imported the deployment for sharedflows and then reapplied it the version number is not getting changed. On terraform plan it gives me "No changes. Infrastructure is up-to-date." and on terraform apply it is "Apply complete! Resources: 0 added, 0 changed, 0 destroyed."

**Comment by scastria** [comment]
I’m not sure what you are asking. If plan says no changes, then that is good. It means your tf file matches what is inside Apigee so everything is in sync and nothing needs to be done. 

From what you said, I am assuming your shared flow has just one revision (revision 1) and that revision is deployed. If you are trying to create a new revision of the shared flow and deploy it, then you must change the zip file of the shared flow so that it’s hash code changes. This causes the shared flow to be uploaded which creates a new revision (revision 2) and because the deployment is referencing the revision number of the shared flow, it causes the deployment to deploy revision 2 replacing the deployment of revision 1.

**Comment by Devajeet1995** [comment]
> I’m not sure what you are asking. If plan says no changes, then that is good. It means your tf file matches what is inside Apigee so everything is in sync and nothing needs to be done.
> 
> From what you said, I am assuming your shared flow has just one revision (revision 1) and that revision is deployed. If you are trying to create a new revision of the shared flow and deploy it, then you must change the content of the shared flow which changes the zip file of the shared flow so that its hash code changes. This causes the shared flow to be uploaded which creates a new revision (revision 2) and because the deployment is referencing the revision number of the shared flow, it causes the deployment to deploy revision 2 replacing the deployment of revision 1.

Yeah, you are correct. Actually, I got confused with something else. But thanks Scastria. Everything is working fine now.
