### ISSUE TITLE
Permission role as empty value

### ISSUE THREAD

**Issue by Tibeno88** [scastria/terraform-provider-apigee#16]
Hello,

In Apigee permissions management, in some cases, the permission value must be set to empty value, as follows
```json
{
    "path": "/applications",
    "permissions": []
}
```
In particular, when we want to specify access only for some api-proxies, or any other resources, the root resource permission doestn't have to give rights.

The REST API of Apigee accept the empty value

https://github.com/scastria/terraform-provider-apigee/blob/7f0c0f0e95a4d3867eaccafc9a00575dcc6b2e82/apigee/resource_role_permission.go#L40
Can you update the rule to permit the empty value ?

**Comment by scastria** [comment]
If you add an apigee_role_permission in your tf file with "get" and apply and then delete that apigee_role_permission from your tf and apply, you will get an empty list inside Apigee.  However, I realize that is not a solution.  I will fix.  I may have to make the permissions property Optional as I don't think the ValidateFunc above is the culprit.  I will get back to you.

**Comment by scastria** [comment]
Stupid me.  It was my own check for empty list that was causing the problem.  Therefore, the fix is not to modify the ValidateFunc above, but just to remove my extra check in the code to allow the permissions list to be empty.

If you try v0.1.36 (when it is done building), you should be able to declare something like this and have it work:

```
resource "apigee_role_permission" "MyRolePermApps" {
  role_name = apigee_role.MyRole.name
  path = "/applications"
  permissions = [
  ]
}
```

**Comment by Tibeno88** [comment]
Yes I had imagined the first proposition but it was not a good solution.

Good that you find the right fix, I'm testing it quikly

**Comment by scastria** [comment]
Any luck with the fix?

**Comment by Tibeno88** [comment]
Sorry, I forgot to answer. Yes, it's all right
