### ISSUE TITLE
Implementing Oauth with machine users

### ISSUE THREAD

**Issue by AgustinICAI** [scastria/terraform-provider-apigee#17]
Hi,

I am using the provider with a machine user (https://docs.apigee.com/api-platform/system-administration/automating-tasks). 

The problem is that the only way machine users to authenticate is with an access token generated previously with an external call to https://yourcompany.login.apigee.com/oauth/token . If you use user/password directly in the provider, it fails. I have implemented this with an "External Data Source".

```
data "external" "apigee_token" {
  program = ["curl", "--location", "--request", "POST",
             "https://yourcompany.login.apigee.com/oauth/token",
             "--header", "Authorization: Basic ZWRnZWNsaTplZGdlY2xpc2VjcmV0",
             "--header", "Content-Type application/x-www-form-urlencoded",
             "--data-urlencode", "grant_type=password",
             "--data-urlencode","username=machineuser@company.com",
             "--data-urlencode", "password=1234567"]
}
```

But what it would be brilliant, is to implement a new functionality for the provider to obtain dynamically the access token when indicating the machine user and the machine password, something like this:
```
provider "apigee" {
  machine_username = "machineuser@company.com"
  machine_password = "1234567"
  organization = "company"
  login_organization = "yourcompany.login.apigee.com"
}
```
What do you think?

**Comment by scastria** [comment]
I didn't know about the machine user thing.  I will see what I can do.

**Comment by scastria** [comment]
When it is done building, try v0.1.38.  I added 2 new properties:
oauth_server
oauth_port

the port is optional and defaults to 443.  The oauth_server is what you specified above as login_organization.  I did NOT add an extra machine_username and machine_password as I just reused username and password.  If you specify an oauth_server then it ASSUMES the username/password is a machine user.  If you do NOT specify an oauth_server, then username/password is the standard Basic authentication user as before.

**Comment by AgustinICAI** [comment]
it works like a charm!!!! Thank you very much!!
