### ISSUE TITLE
support for keystores and reference pointers

### ISSUE THREAD

**Issue by bertramn** [scastria/terraform-provider-apigee#19]
This is more a question rather than an issue report. I noticed that [keystores](https://docs.apigee.com/api-platform/system-administration/keystores-and-truststores) are not supported by the provider. Was there any issue building the provider resource or is that something that was simply not yet been implemented?

**Comment by scastria** [comment]
Are you requesting that keystores be added to the provider?

**Comment by bertramn** [comment]
I have an Apigee setup that uses lots of keystores and also use these keystore ref pointers and aliases for easy management. Happy to ship in some development and testing.

**Comment by scastria** [comment]
LabiedYounes has added support for all 3 of your requested resource types.  I have approved and released keystores and references.  I still have to review aliases.

**Comment by scastria** [comment]
I just added support for aliases based off of LabiedYounes PR.
