### ISSUE TITLE
Add option to not append the port in APIGEE_SERVER

### ISSUE THREAD

**Issue by anderson-marques** [scastria/terraform-provider-apigee#20]
A recommended good practice is to put the Apigee Management API itself behind Apigee as a proxy to increase the control over it. The current implementation adds the port after the `APIGEE_SERVER` URL what makes that impossible.

Example: `https://apis.my-company.com/apigee-management-api` -> `https://apigee.googleapis.com`

But the current implementation results in: `https://apis.my-company.com/apigee-management-api:443/v1/organizations...`

It would be helpful to ignore the port when not defined since 443 is the default for `https:`. 

Suggestion: If ends with `443` add `https`. If not add `http`. If not set do not add `:%d`.

By the way, excellent job!

https://github.com/scastria/terraform-provider-apigee/blob/6bce05833d7e5d76c0102751469a0be622feb140/apigee/client/client.go#L160

**Comment by scastria** [comment]
Ah, I see the issue.  I provided a parameter for server which is implied to be a hostname.  You provided a server value equal to a server AND a path after the server so my code blindly adds the port at the end of the server.  Rather than mess with the port, I will add a new parameter called ServerPath or something like that.

**Comment by scastria** [comment]
When v0.1.39 finished building, see if it resolves this issue.  In your example above, you would configure the provider as:

server = apis.my-company.com
server_path = apigee-management-api/v1

**Comment by anderson-marques** [comment]
Thank you @scastria ! I will test version v0.1.39 setting the provider like you indicated.

**Comment by scastria** [comment]
How did you test go?  Did it work?  Can I close this issue?

**Comment by scastria** [comment]
I will assume it worked
