### ISSUE TITLE
unable to configure provider for opdk migration

### ISSUE THREAD

**Issue by rohan1234** [scastria/terraform-provider-apigee#30]
Hello @scastria 
"As we have OPDK set up on the private cloud so how can we perform development"
please find my code

```
terraform {
  required_providers {
    apigee = {
      source  = "scastria/apigee"
      version = "~> 0.1.0"
    }
  }
}
provider "apigee" {
  username = "apigee@opdk.com"
  password = "Apigee@123"
  organization = "myorg"
  server = "11.22.33.44:9000" // ip and port where apigee opdk is running
  port = 80
  oauth_port = 80
}

resource "apigee_proxy" "example" {
  name = "ShawnTest"
  bundle = "C:\\Users\\LP45\\Desktop\\opdk-migration\\demo_rev1_2021_10_26.zip"
  bundle_hash = filebase64sha256("C:\\Users\\LP45\\Desktop\\opdk-migration\\demo_rev1_2021_10_26.zip")
}
```

as soon I run this code I got the below error 

![image](https://user-images.githubusercontent.com/79567006/138814549-ff7ac388-7743-4f9d-995a-6671f15a8af3.png)

also, one thing I would like to tell you in the error message
"Error: Status 500: Message: Internal Server Error: Post "https://11.22.33.44:9000/v1/organizations/myorg/apis?action=import&name=ShawnTest": EOF"
it is passing to HTTPS but for now, we haven't enabled any security for it this is working on HTTP only

**Comment by scastria** [comment]
The server parameter is for the server only, not the port.  The port parameter is for the port.  I can add an extra scheme parameter to the provider config so you can specify http instead of https, but I will only do that if you still are having problems and need this change.

**Comment by rohan-git-neos** [comment]
@scastria hey I am not working on this right now but in further might anyone encounter the same so it's good if you made changes accordingly
