### ISSUE TITLE
Resource instance key must be given in square brackets.

### ISSUE THREAD

**Issue by NAbiKeerthana** [scastria/terraform-provider-apigee#31]
Hello @scastria ,

When I try to import the already existing apigee reference with below command,

-terraform import apigee_reference.apis-demo.gcp non-prod:apis-demo.gcp

I am getting the below error,

2021-11-02T06:57:51.162Z [INFO]  CLI command args: []string{"import", "apigee_reference.apis-demo.gcp-ref", "non-prod:apis-demo.gcp-ref"}

│ Error: Invalid address
│ 
│   on <import-address> line 1:
│    1: apigee_reference.apis-demo.gcp
│ 
│ Resource instance key must be given in square brackets.

Could you please help me with a solution for this issue ?

**Comment by scastria** [comment]
This is a terraform generic question and not specific to the Apigee provider. Therefore, please seek help in the terraform community.
