### ISSUE TITLE
Debug terraform-provider-apigee

### ISSUE THREAD

**Issue by NAbiKeerthana** [scastria/terraform-provider-apigee#32]
Hello @scastria ,

I need to debug the terraform-provider-apigee for an issue. Is there any way to do that by giving a command from my Terraform CLI.
I have implemented a functionality to add certs to truststores and When I run the below command, I am getting the below mentioned issue.

terraform import apigee_cert.trustStore envName:truststoreName:certName

and the issue:
![image](https://user-images.githubusercontent.com/86286051/144623969-9985b954-f948-4496-bc3f-46b18d94c9e0.png)

Appreciate your help. Thanks !

**Comment by scastria** [comment]
The only way I debug is to set TF_LOG to Debug. This will cause tons of debug output to print during the Apigee provider usage. If you search the output for Apigee Management API, you will find every single API call made to the Apigee server. 

My best guess is that this is another case of the Apigee Management API being inconsistent between the different versions of Apigee. I tested with the Private Cloud version. You are probably using a different version and the provider needs to be tweaked slightly to accommodate your version’s API.

**Comment by NAbiKeerthana** [comment]
Sure. Let me take a look at it. Thanks !
