### ISSUE TITLE
[Question] Resources proxy update?

### ISSUE THREAD

**Issue by arnaduga** [scastria/terraform-provider-apigee#4]
Is there a way to update resources proxy files, like `resources/jsc`?

I saw the API endpoint `GET /organizations/{org_name}/resourcefiles/{resource_type}/{resource_name}` in the [doc](https://apidocs.apigee.com/docs/resource-files/1/routes/organizations/%7Borg_name%7D/resourcefiles/%7Bresource_type%7D/%7Bresource_name%7D/get)

Could it do the job?

**Comment by scastria** [comment]
Not sure.  I have never even noticed this resource file ability.  I can add support for resource files, but I would want to make sure it will resolve whatever problem you are trying to solve.  You sound unsure if resource files will even work so before I invest time in adding support for them in the provider, can you make sure you really need them?

**Comment by arnaduga** [comment]
In my customer context, there is a resource file that basically contains a JSON string. It is use by a developed API to provide certain service. It is a kind of parameter file.

I woudl like to update this file by scripting, terraforming.

However, as you pointed, I'm not comfrotable with this adopted logic. Today, I got a meeting with the additional service PO and he admitted this file usage is may be not so convenient and they may swith to KVM.

So, I suggest to close this question.

Thanks!

**Comment by scastria** [comment]
I had some spare time so I added support for resource files within orgs, environments, and proxies.  v0.1.20 is building now

**Comment by arnaduga** [comment]
Sorry @scastria, I missed this information!

Let me check and come back for feedback.

Thanks!

**Comment by arnaduga** [comment]
Hmm... Strange. 

No error, but nothing happened and I cannot find my file.

I tested:
```

resource "apigee_environment_resource_file" "example" {
  environment_name = "test"
  type             = "js"
  name             = "myNameENV.js"
  file             = "resourceFiles/test.js"
  file_hash        = filebase64sha256("resourceFiles/test.js")
}

resource "apigee_organization_resource_file" "example" {
  type      = "js"
  name      = "myNameORG.js"
  file      = "resourceFiles/test.js"
  file_hash = filebase64sha256("resourceFiles/test.js")
}
```

But I can not locate neither `myNameENV.js` nor `myNameORG.js` file in the proxy or anywhere else in the console.

However, the terraform succeeded:
```
$ terraform --version
Terraform v0.13.2
+ provider registry.terraform.io/scastria/apigee v0.1.22

Your version of Terraform is out of date! The latest version
is 0.14.3. You can update by downloading from https://www.terraform.io/downloads.html

$ terraform apply -auto-approve
apigee_environment_resource_file.example: Refreshing state... [id=test:js:myName]
apigee_environment_resource_file.example: Destroying... [id=test:js:myName]
apigee_organization_resource_file.example: Creating...
apigee_environment_resource_file.example: Destruction complete after 1s
apigee_organization_resource_file.example: Creation complete after 1s [id=js:myNameORG]
apigee_environment_resource_file.example: Creating...
apigee_environment_resource_file.example: Creation complete after 0s [id=test:js:myNameENV]

Apply complete! Resources: 2 added, 0 changed, 1 destroyed.
```

**Comment by scastria** [comment]
From my understanding, organization and environment resource files cannot be found anywhere in the UI.  If you test a proxy resource file, then you can look inside the proxy in the UI and see the added resource files.  If you want to see the org or env resource files, you have to use the management API to read them back.

**Comment by arnaduga** [comment]
Ok, then, I used the wrong vocabulary.

I expected this kind of file attachment:
![image](https://user-images.githubusercontent.com/56150873/103571622-8284c900-4ecb-11eb-837f-a5c3baeb1240.png)

This allows also editing directly from the console...

**Comment by scastria** [comment]
Yes, that is a proxy resource file in your screenshot, but your test above was an organization and environment resource file.

**Comment by arnaduga** [comment]
My bad... I saw you added env and org file, but did not see the PROXY file ... which works like a charm.

Sorry about that.

Thank you for the 1.22 version! 👍
