### ISSUE TITLE
Bad Gateway 501 or Unauthorized 401

### ISSUE THREAD

**Issue by pysiok1983** [scastria/terraform-provider-apigee#41]
Hi,
I am trying to use this repo but seems I have an issue using this terraform provider for APIgeeX. I generated token from the shell:
```
gcloud auth activate-service-account --key-file=sa.json
gcloud auth print-access-token
```
and using this token for the provided. All the time I am receiving the same error:

```
apigee_proxy.proxy_001: Creating...
╷
│ Error: Status 401: Message: Unauthorized: 
│ 
│   with apigee_proxy.proxy_001,
│   on 04_apix.tf line 159, in resource "apigee_proxy" "proxy_001":
│  159: resource "apigee_proxy" "proxy_001" {
```
Are you able to help?

**Comment by scastria** [comment]
If you set environment variable TF_LOG to TRACE, you should get a lot more detail such that you can see the actual rest api call that is failing.

**Comment by scastria** [comment]
Also, how are you configuring the provider? Obviously, you can obscure any secret information, if needed.
