### ISSUE TITLE
Support for Apigee X KVM entries

### ISSUE THREAD

**Issue by otheriault** [scastria/terraform-provider-apigee#50]
Hello, I am still pretty new to both Terraform and Apigee. I came across this great Apigee Terraform provider, but I think there is a disconnect with the `apigee_environment_kvm` resource and the actual KVM entries for Apigee X. I tried to set KVM entries using the mentioned Terraform resource and this did create the KVM successfully, but this does not seem to populate the entries. Maybe I am just doing something wrong here?

Apigee X has a dedicated API for managing KVM entries (https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.keyvaluemaps.entries) and I am asking if for Apigee X environments there should be a new `apigee_environment_kvm_entries` resource?

Something like this
```
resource "apigee_environment_kvm_entry" "example-first" {
  environment_name = "dev"
  kvm_name = "example"
  name = "first"
  value = "firstValue"
}
```

Thanks

**Comment by scastria** [comment]
See if v0.1.51 fixes this issue.  It was a PR from a contributor.  I am no longer able to test anything related to Apigee.

**Comment by gavinbd** [comment]
I have recently pushed a commit for this. The resource schema is the same to support both apigee formats, its mandatory to have encrypted set on apigee X followed with sensitive_entry for kv's

`resource "apigee_environment_kvm" "kvm" {
  environment_name = var.apigee_env
  name             = "n"
  encrypted        = true
  sensitive_entry  = {
    k: "value"
  }
}
`

**Comment by otheriault** [comment]
I tried this originally, but then I got an error stating that the `entry` property was missing. Then if I provide both `entry` and `encrypted_entry` I got another error saying that these are mutually exclusive. So I ended up with
```
resource "apigee_environment_kvm" "kvm" {
  environment_name = var.apigee_env
  name             = "n"
  encrypted        = true
  entry  = {
    k: "value"
  }
}
```
which did not store any entry values in the KVM.

**Comment by otheriault** [comment]
I am still new to Terraform and the dependency management. In fact, I was not on the latest version as I thought. @scastria @gavinbd thanks for taking the time. Everything does work properly with the KVM entries with this version.
