### ISSUE TITLE
apigee_proxy_deployment - error on update

### ISSUE THREAD

**Issue by bstraehle** [scastria/terraform-provider-apigee#54]
<strong>Apigee Edge for Private Cloud: 4.5.1</strong>
<strong>Terraform Apigee provider: 0.1.51</strong>

Resource <strong>apigee_proxy</strong> works and <strong>apigee_proxy_deployment</strong> works on <strong>create</strong> but fails on <strong>update</strong> with the following error:

```
Error: Status 400: Message: Bad Request: {
  "code" : "distribution.DeploymentPathConflict",
  "message" : "Path /abc conflicts with existing deployment path for revision 123 of the APIProxy abc-api in organization xyz-org, environment dev",
  "contexts" : [  ]
}
```

For reference, resource <strong>apigee_shared_flow_deployment</strong> works for both create and update.

**Comment by bstraehle** [comment]
Using a different zip bundle name avoids the issue.  We will need a change to our CD pipelines, but it is workable.  Thanks.

**Comment by bstraehle** [comment]
Using a different zip bundle name avoids the issue.  We will need a change to our CD pipelines, but it is workable.  Thanks.

**Comment by AlbertoMonteiro** [comment]
I have the same issue, what did you changed @bstraehle ?

Can you provide an example?
