### ISSUE TITLE
Apigee NG: Key value map operations dont seem to line up with the api docs:

### ISSUE THREAD

**Issue by davidmitchell2019** [scastria/terraform-provider-apigee#6]
Key value map operations dont seem to line up with the api docs:

https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.keyvaluemaps/create

Error: Status 400: Message: Bad Request: {
"error": {
"code": 400,
"message": "Invalid JSON payload received. Unknown name "entry" at 'key_value_map': Cannot find field.\nInvalid JSON payload received. Unknown name "EnvironmentName" at 'key_value_map': Cannot find field.\nInvalid JSON payload received. Unknown name "ProxyName" at 'key_value_map': Cannot find field.",
"status": "INVALID_ARGUMENT",
"details": [
{
"@type": "type.googleapis.com/google.rpc.BadRequest",
"fieldViolations": [
{
"field": "key_value_map",
"description": "Invalid JSON payload received. Unknown name "entry" at 'key_value_map': Cannot find field."
},
{
"field": "key_value_map",
"description": "Invalid JSON payload received. Unknown name "EnvironmentName" at 'key_value_map': Cannot find field."
},
{
"field": "key_value_map",
"description": "Invalid JSON payload received. Unknown name "ProxyName" at 'key_value_map': Cannot find field."
}
]
}
]
}
}

**Comment by scastria** [comment]
I see no way to fix this based on the Apigee NG API docs.  The docs for the creation of a KVM only take a name and an encrypted boolean.  I see no way to handle the entries for the KVM, create them, update them, or delete them.  Perhaps this is a sign Apigee NG Management API is not ready??

**Comment by davidmitchell2019** [comment]
Could well be, i can create a proxy with just a KvM operation policy and deploy, undeploy it to create the kvm entry so il do that

**Comment by scastria** [comment]
I got official word from Google that KVM entry support is ONLY accessible through policies of proxies with Apigee NG.  Developers can use Property Sets as an alternative means for storing static configuration data.  So I guess I should add support for property sets.
